name: Deploy PHAR via FTP

on:
  push:
    branches:
      - main # Change this to your deployment branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Update this to your PHP version
          
      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build PHAR
        run: php -d phar.readonly=0 bin/build.php

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ls.encodeunlimited.com
          username: u600962660.asankaj
          password: ${{ secrets.PHAR_FTP_PASSWORD }}
          port: 21
          local-dir: ./build/
          server-dir: /home/u600962660/domains/ls.encodeunlimited.com/public_html/
          # exclude: |
